// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driverMessage.proto

package executors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DriverMessage struct {
	Iid                  string   `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	MetricsJSON          string   `protobuf:"bytes,3,opt,name=metricsJSON,proto3" json:"metricsJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverMessage) Reset()         { *m = DriverMessage{} }
func (m *DriverMessage) String() string { return proto.CompactTextString(m) }
func (*DriverMessage) ProtoMessage()    {}
func (*DriverMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cb16e492887c129, []int{0}
}

func (m *DriverMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverMessage.Unmarshal(m, b)
}
func (m *DriverMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverMessage.Marshal(b, m, deterministic)
}
func (m *DriverMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverMessage.Merge(m, src)
}
func (m *DriverMessage) XXX_Size() int {
	return xxx_messageInfo_DriverMessage.Size(m)
}
func (m *DriverMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DriverMessage proto.InternalMessageInfo

func (m *DriverMessage) GetIid() string {
	if m != nil {
		return m.Iid
	}
	return ""
}

func (m *DriverMessage) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DriverMessage) GetMetricsJSON() string {
	if m != nil {
		return m.MetricsJSON
	}
	return ""
}

func init() {
	proto.RegisterType((*DriverMessage)(nil), "executors.DriverMessage")
}

func init() { proto.RegisterFile("driverMessage.proto", fileDescriptor_0cb16e492887c129) }

var fileDescriptor_0cb16e492887c129 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x29, 0xca, 0x2c,
	0x4b, 0x2d, 0xf2, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4c, 0xad, 0x48, 0x4d, 0x2e, 0x2d, 0xc9, 0x2f, 0x2a, 0x56, 0x8a, 0xe6, 0xe2, 0x75, 0x41,
	0x56, 0x21, 0x24, 0xc0, 0xc5, 0x9c, 0x99, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0x62, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0x30, 0x29, 0x30, 0x6a,
	0xf0, 0x06, 0x41, 0x79, 0x42, 0x0a, 0x5c, 0xdc, 0xb9, 0xa9, 0x25, 0x45, 0x99, 0xc9, 0xc5, 0x5e,
	0xc1, 0xfe, 0x7e, 0x12, 0xcc, 0x60, 0x1d, 0xc8, 0x42, 0x4e, 0x9a, 0x5c, 0x12, 0x29, 0xa9, 0x7a,
	0x99, 0xc5, 0xa9, 0x7a, 0x25, 0xa5, 0x49, 0xa9, 0x45, 0x39, 0x99, 0x79, 0x7a, 0x69, 0x89, 0x39,
	0xc9, 0xf9, 0x7a, 0x99, 0xf9, 0x4e, 0xa8, 0xd6, 0x26, 0xb1, 0x81, 0x5d, 0x66, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x75, 0xc2, 0xad, 0xb0, 0x00, 0x00, 0x00,
}
